defaults: &defaults
  host: localhost
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: idea_machine_development

test:
  <<: *defaults
  database: control_test

# set these environment variables on your prod server
development:
  <<: *defaults
  database: ideamachiner-production
  host: flame.mongohq.com
  port: 27037
  username: ideamachiner
  password: ideamachiner